### ISSUE TITLE
Lock page during postback

### ISSUE THREAD

**Issue by exyi** [riganti/redwood#45]
Currently the framework allows to create several concurrent postbacks. E.g. when the user clicks the button twice, two postbacks are sent to the server and if the responses come in different order, the viewmodel can break.

**Comment by tomasherceg** [comment]
There are several solutions and I don't know which one is the best. 

1. Prevent the postback when another postback is active. The advantage is that this behavior also helps to prevent e.g. creating duplicate items in the DB when the user double clicks the button. In combination with some UpdateProgress control which displays some loading icon, this is my favorite.

2. Allow the second postback and when the response comes from the first one, drop it because it is outdated. This is the way ASP.NET WebForms behave.

3. Put the postback in some queue and post it to the server when the current postback is finished. I don't think this is suitable for most scenarios however I can imagine this solution for e.g. the Timer control which posts back each minute - in case there is some postback, the Timer will wait until it is finished. But we can implement this behavior directly in the Timer control, it does not have to be the framework feature.

**Comment by exyi** [comment]
Maybe we can queue postbacks internaly but disable all controls performing actions. This will prevent user enqueuing many unwanted requests (and creating duplicates in db) and make posting back in any time possible.

**Comment by tomasherceg** [comment]
If you prevent the user to use the controls during the postback, it is the solution 1 and there is no need for the queue at all.

**Comment by tomasherceg** [comment]
For the milestone 0.5 I have decided that it will be enough to create the UpdateProgress control that can display an overlay with a loading animation. 
If the developer decides not to use it, then the user will  be able to create multiple postbacks but it is his problem.
