### ISSUE TITLE
Failure while building the Visual Studio extension project due to missing Owin.1.0.0.0.nupkg

### ISSUE THREAD

**Issue by TomasHubelbauer** [riganti/redwood#66]
Building the `Redwood.VS2015Extension` project, I'm greeted with an error which states the following:

```
Could not add the file "Packages\Owin.1.0.0.nupkg" to the zip package "bin\Debug\Redwood.VS2015Extension.vsix".
Could not find file '…\redwood\src\Redwood.VS2015Extension\Packages\Owin.1.0.0.nupkg'.
```

The file is, indeed, missing. I have noticed that the `Packages` folder is included in the solution for the project presumably because of the PowerShell scripts, and all NUPKG package files are ignored, but also included in the solution. Of these files, all of them are located except precisely `Owin.1.0.0.nupkg`.

I've restored Nuget packages, no references are in an error state, only the described file is missing. Is this perhaps a bug where clone followed by a clean build doesn't correctly restore some packages?

**Comment by tomasherceg** [comment]
In the Redwood.VS2015Extension/Redwood.VS2015Extension.csproj there is a pre-build script that copies the nupkg files from the packages folder. 
The package Owin.1.0.0 is quite weird because in Visual Studio it resolves in the folder Owin.1.0.0 however on the CI server it resolves to the Owin.1.0 folder - I don't know why. 
This may be the cause of the problem why the file is not copied.

However this issue will be gone soon because Redwood nuget package will be published to the official NuGet feed and there'll be no need to embed the packages in the Visual Studio Extension.

**Comment by TomasHubelbauer** [comment]
Interestingly, on another computer, the Owin package resolved perfectly.

**Comment by tomasherceg** [comment]
I believe that the package was named Owin.1.0 previously and then they updated it to Owin.1.0.0. However if you have the old version of the package in some NuGet cache, it resolves wrong.
